---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: kaleb@coded.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: kaleb@coded.io
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api-token
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: kaleb@coded.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: kaleb@coded.io
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api-token
              key: api-token
