---
creation_rules:
- path_regex: ansible/.*\.sops\.ya?ml
  age: >-
    age16ptwsrpuqmlevjqz8slzd9zt6hd700av6q2yszc2x7ypltzjhfaq929qc5
- encrypted_regex: '^(data|stringData)$'
  path_regex: cluster/.*\.sops\.ya?ml
  age: >-
    age16ptwsrpuqmlevjqz8slzd9zt6hd700av6q2yszc2x7ypltzjhfaq929qc5
