apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-system
  labels:
    app.kubernetes.io/name: postgres
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: postgres
  ports:
  - port: 5432
  loadBalancerIP: "192.168.43.2"
