apiVersion: v1
metadata:
    name: flux-system
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:KmnHfx3TNCcu3w+7qMMXxFCKeRYcHSE9tFXcT33rrxgeVXd2QvP0r1hqr2iWAj5fSNxx55CMzJprel5RuUHcucS6arWXY7vScwXkC5qyGUeYxdk60d0sy0o5Zt/zYvkAcDVTHnVkVc870YBvrx15EvwJwunevB79R0FCu3yNRr9sV57kCeQcLt6EcpXq3W/gfeUiDLxUlb8L0AmpZrjfx2M3qL/xPp3M8wFKx16yr4zb+uGiGDbm6QIf4x4YHwmecfdtpjtzuarjTpe6BOmlECbovFIqTnIKvUthPDlMAWcKysj24bQv0L4KmNo7AjDUw0etTbHnih3v2iD5EhfLTNl3FWjOMX8t5PozZ8aeIkUWGGD8MxjAPx84oVazbT4v38iYC3IfnjPFwxLb1zq7rcjuhaMqnCuvnfJxoTBXb6dtbZkq1xj6KqHAxkvk561agYMBXTllSsjq486ipqNkWByoRFw/9svKWMRfLN6T/2N9nduMGj8cSFCJKrMUEVdr2OoSNo7XMkF6G/p9012iNpeOYMwF+gt/YIHJ60j709Z3jN3T1ykZy5NCxVX67i01ug9PlGye3/647bEkOV63k7VWjGvKLw1u1OE2sA3zrehsNzxRZE1TFEQhPMUNFBEz92jqs8QodaEcDwsbh2CGRDuKEyzDWsRNIa1qUF6sISDYhpPj+JlQqzrjNg0b8ClRvARH0A==,iv:oyktKlWCH1WiHn0IjJty387MUWZemnoOHo6L4VzAjRE=,tag:Crlxp+1qNsRfIJzaaUQ0Ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:10qALkR/7gjbS8MuniGECwfMrI+vx06qgwH/qmIFOeud7mcCpR/ClQuxAiurDJoDXpRmAtqOwBddxU9yzUB1q77EFggU/BpKeB/z0hKgj3mPnNi6WlKkUGWotR38nKZ4aappAMwUpQ5DfkFAVJfpThKsYIBBjCHx,iv:qHPDi/d2tgk9kwXqzMiFp4wUZ2TDa2DgvOgQHEyM3+U=,tag:E3TO+YSsQ3tZO3D8vHzjqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9B91CNCtiOAESZaZ1lyexhpe6/fpfpW//0n7b2d2yMErFErmQYGVoMMocw0YOfmZ/rt41sY1J+vETYiLjCnsp6MQHpFRiufTCiq3rXbuG3qBGPJg4Ovy4rwxuzVwNyNnEujh4SHZU47v6IrJ7+RlaWopZ9JX1clkrwED9IKyPVTXiGJHPfAGsirdOfOLVUf66TZ3uqcScgyETTjASI4JuNfoqwUY7p5kEPjIMBug6UX45PoVFjx1PZkiSQaNhqIqSlPh3q+TrVhQkl8SkaL0slAn8N26QulB3A8j8F2mZLaGtFcG,iv:HjioEyfA/iUG+06TF45eDO54lBVx9wGfQ79DLSTw9ns=,tag:W1nahalBltRCbBR8XR96ZQ==,type:str]
kind: Secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ptwsrpuqmlevjqz8slzd9zt6hd700av6q2yszc2x7ypltzjhfaq929qc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINzVrK1lHZk1QaWRMVUpx
            UjF2NG9QK1V0L05SMFQ5aTkrcUhDYVdEZ2hJCnQ5bGF5RlM4dFQ1TzJreTAvdFlw
            d0d3dTBmMTBWQTF2UzZXVjN5MjdiNWcKLS0tIFhmU1A4U3R1djRza2w5TmlNR1FY
            QmFnQlFQano5SUdtRnFkNE9wcy82OE0KU1TbClDWWLl6z1X6NB1FddDUMrFLAHqR
            W86HuerwMnfXViFDmuyCa10qGYI0C42iy3gFQMwJ4xNtupoD8TYaoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T05:03:08Z"
    mac: ENC[AES256_GCM,data:8RhLz65on/pRDzlOsV0/Aqvcvf4KgnqsUZIyl5NJ3kkTu2/GEitwwzIqtLOPf1pa5406yzZYu3/bkNcxuQsBb5hMNtC1M7YEZN90Cr0eAbSsSKY9rHDu8LBcPf5P6javUMcPw/1XstK2ZCajs30liTBlQpsFIubchC0DfwElXqo=,iv:7KHFKho/32gp3dVjma01lT6HpZcCZtqmvYDU7fmUtjI=,tag:d/0urIPUvkRTInm5gu/XUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
metadata:
    name: sops-age
    namespace: flux-system
data:
    age.agekey: ENC[AES256_GCM,data:s39RUo4xsfrLGiacsMgM5FIhFCRRtwioQnm3xR11bSeENoLYRmU7q/+/kbkMiwHQU8kwZESq5xqo/oYrsmSBewdnUqobbFpk2unQhL3qyO+wAuz8YhALuCbfNzRcrVAjRwzFizOGFdReV1NvrK5L+nLWh2AyNA7CmK9QStH3XnL+1hru9LbqGJm0vXDQ0c2LjZKL0MExvW0f+pGUvXOmYNHkJpkPzLG5APZbD/GS3bE4ZU+d2ngijeWstAh2ZefinH+0hvtB9hAjq9OHfQU+er5eGsl9gyPJWujrTuazeZ6v+ZQdbQ+IAV59Nhi1+WpgyuqPdHIJeSaVxTMI,iv:1y/QDLHHu77XXGj5NuuBrHWyUIIvtG2BktU1GC6/6qM=,tag:KZs9KhPv3BIoZKouJSaDNw==,type:str]
kind: Secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ptwsrpuqmlevjqz8slzd9zt6hd700av6q2yszc2x7ypltzjhfaq929qc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINzVrK1lHZk1QaWRMVUpx
            UjF2NG9QK1V0L05SMFQ5aTkrcUhDYVdEZ2hJCnQ5bGF5RlM4dFQ1TzJreTAvdFlw
            d0d3dTBmMTBWQTF2UzZXVjN5MjdiNWcKLS0tIFhmU1A4U3R1djRza2w5TmlNR1FY
            QmFnQlFQano5SUdtRnFkNE9wcy82OE0KU1TbClDWWLl6z1X6NB1FddDUMrFLAHqR
            W86HuerwMnfXViFDmuyCa10qGYI0C42iy3gFQMwJ4xNtupoD8TYaoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T05:03:08Z"
    mac: ENC[AES256_GCM,data:8RhLz65on/pRDzlOsV0/Aqvcvf4KgnqsUZIyl5NJ3kkTu2/GEitwwzIqtLOPf1pa5406yzZYu3/bkNcxuQsBb5hMNtC1M7YEZN90Cr0eAbSsSKY9rHDu8LBcPf5P6javUMcPw/1XstK2ZCajs30liTBlQpsFIubchC0DfwElXqo=,iv:7KHFKho/32gp3dVjma01lT6HpZcCZtqmvYDU7fmUtjI=,tag:d/0urIPUvkRTInm5gu/XUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
