apiVersion: v1
metadata:
    name: postgres-secrets
    namespace: postgres-system
data:
    #ENC[AES256_GCM,data:KFgtvgObdLz3VcJa9vhIheu0JAdgjsIuLeIgHSNhEdokqL4diS+Kc2ZmPSgxpobbVIwb5yu5mR4SLaePA+HPziox2nDOLg==,iv:BYJJ0cqtSNyLvNX3TonVXcesglnXnEIurj0w7ogWL8Y=,tag:OrHQCfzPm7Mi8noMKfMCSw==,type:comment]
    password: ENC[AES256_GCM,data:WaH1p9abcnxHdW+Smq94KUf3oI/bSXs3GgHvcePkSug70i63fUgsc2yE83HtctR8Mky8Lg0hCxIapzGfODYNgeE/imwK16DmoGflkFVUgOQoW77i,iv:r2kSW6coRD+frB6Kjf/QE9WglqKOntUhAxqCgf+6108=,tag:saljri3Z2jBU0I5zJWm9nA==,type:str]
kind: Secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ptwsrpuqmlevjqz8slzd9zt6hd700av6q2yszc2x7ypltzjhfaq929qc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINzVrK1lHZk1QaWRMVUpx
            UjF2NG9QK1V0L05SMFQ5aTkrcUhDYVdEZ2hJCnQ5bGF5RlM4dFQ1TzJreTAvdFlw
            d0d3dTBmMTBWQTF2UzZXVjN5MjdiNWcKLS0tIFhmU1A4U3R1djRza2w5TmlNR1FY
            QmFnQlFQano5SUdtRnFkNE9wcy82OE0KU1TbClDWWLl6z1X6NB1FddDUMrFLAHqR
            W86HuerwMnfXViFDmuyCa10qGYI0C42iy3gFQMwJ4xNtupoD8TYaoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T22:55:15Z"
    mac: ENC[AES256_GCM,data:j0vbS6n51x5xfxHeGwK0nUqSe654h7Z6NZHNyKzkWejNrnHX+qUNz5I+xEHDsFR02fTVwXPWfd3lvoXcUTZJf7v1m1fzo030QjelaauIykHqCTL1/qysnMKZIuz1UM0pNXah7MDyI2ZZz89LHD/a4Oyp9CUHQl9XjvXp4UDm+As=,iv:65i2UPdImJ7yf6B4xSeBsgibJaH7qFzoFOm5aYS9y2U=,tag:3bpzm+4NvpMjWpbeKCJstg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
